In [2]:
import pandas as pd
import numpy as np 
import os
import librosa

In [3]:
DEAM_dataset = "../data/DEAM"
PMEMO_dataset = "../data/PMEmo2019"

In [4]:
pmemo_annotations = PMEMO_dataset + "/annotations/static_annotations.csv"
pmemo_songs = PMEMO_dataset + "/chorus"
pmemo_metadata= PMEMO_dataset + "/metadata.csv"

PMEMO_ann= pd.read_csv(pmemo_annotations, sep =",")
PMEMO_metadata = pd.read_csv(pmemo_metadata, sep =",")

In [5]:
PMEMO_ann

     musicId  Arousal(mean)  Valence(mean)
0          1         0.4000         0.5750
1          4         0.2625         0.2875
2          5         0.1500         0.2000
3          6         0.5125         0.3500
4          7         0.7000         0.7250
..       ...            ...            ...
762      993         0.8625         0.7625
763      996         0.8750         0.5625
764      997         0.7125         0.6625
765      999         0.8750         0.7750
766     1000         0.6625         0.5750

[767 rows x 3 columns]

In [6]:
mp3_df = pd.DataFrame([], columns=["musicId", "mp3_file"])

for file in os.listdir(pmemo_songs):
    data = os.path.join(pmemo_songs, file)

    audio, sr = librosa.load(data, sr = 44100)
    mp3_df = pd.concat([mp3_df, pd.DataFrame([{"musicId": file.replace(".mp3",""), "mp3_file" :audio}])])

mp3_df

In [ ]:
PMEMO_ann["musicId"] = PMEMO_ann["musicId"].astype(str)
PMEMO_metadata["musicId"] = PMEMO_metadata["musicId"].astype(str)
mp3_df["musicId"] = mp3_df["musicId"].astype(str)

pmemo = PMEMO_ann.join(PMEMO_metadata.set_index("musicId"), "musicId")\
                 .join(mp3_df.set_index("musicId"), "musicId")\
                 .drop(columns=["fileName","duration", "chorus_start_time", "chorus_end_time"])\
                 .rename(columns={"Valence(mean)": "Valence", "Arousal(mean)":"Arousal"})

In [ ]:
pmemo

,musicId,Arousal,Valence,title,artist,album,mp3_file
0,1,0.4000,0.5750,Good Drank,2 Chainz,"Def Jam Presents: Direct Deposit, Vol. 2","[0.0, -8.106964e-16, -5.9545294e-16, 1.866628e..."
1,4,0.2625,0.2875,X Bitch (feat. Future),21 Savage,Savage Mode,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,5,0.1500,0.2000,No Heart,21 Savage,Savage Mode,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,6,0.5125,0.3500,Red Opps,21 Savage,Red Opps,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,7,0.7000,0.7250,Girls Talk Boys,5 Seconds Of Summer,Ghostbusters (Original Motion Picture Soundtrack),"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...
762,993,0.8625,0.7625,Stay,Zedd,Stay,"[0.0, 2.9683367e-16, 2.2974556e-16, -6.1721226..."
763,996,0.8750,0.5625,Trouble,offaiah,Trouble,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
764,997,0.7125,0.6625,A Supplementary Story : You Never Walk Alone,방탄소년단,YOU NEVER WALK ALONE,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
765,999,0.8750,0.7750,Outro : Wings,방탄소년단,YOU NEVER WALK ALONE,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
766,1000,0.6625,0.5750,Spring Day,방탄소년단,YOU NEVER WALK ALONE,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [ ]:
#pmemo.to_pickle("./data/PMEmo_useful")

In [ ]:
deam_metadata_2013 = pd.read_csv(DEAM_dataset+"/DEAM_metadata/metadata_2013.csv", sep =",")
deam_metadata_2014 = pd.read_csv(DEAM_dataset+"/DEAM_metadata/metadata_2014.csv", sep =",")                    
deam_metadata_2015 = pd.read_csv(DEAM_dataset+"/DEAM_metadata/metadata_2015.csv", sep =",")

In [ ]:
deam_metadata_2013 = deam_metadata_2013.drop(columns=["start of the segment (min.sec)", "end of the segment (min.sec)", "Genre", "file_name"])\
                                       .rename(columns = {"song_id": "musicId", "Artist" : "artist", "Song title" : "title"})
deam_metadata_2013

,musicId,artist,title
0,2,The New Mystikal Troubadours\t,\tTonight A Lonely Century\t
1,3,Kevin MacLeod\t,\tDD Groove\t
2,4,Kevin MacLeod\t,\tSlow Burn\t
3,5,My Bubba & Mi\t,\tNothing Much\t
4,7,Kevin MacLeod\t,\tHustle\t
...,...,...,...
739,995,Benjamin Bret\t,\tHonte De Toi\t
740,996,Jahzzar\t,\tFireworks\t
741,997,Halloween\t,\tMonster On Campus\t
742,999,Jahzzar\t,\tSo Easy\t
743,1000,Republic Of Lights-Got You Surrounded \t,\t Single\t

In [ ]:
deam_metadata_2014 = deam_metadata_2014.drop(columns = ["segment start", "segment end", "last.fm labels"])
deam_metadata_2014.columns

Index(['Id', 'Artist', 'Album', 'Track', 'Genre'], dtype='object')

In [ ]:
deam_metadata_2015 = deam_metadata_2015.drop(columns=["Filename", "album", "genre", "Unnamed: 6"])\
                                       .rename(columns = {"id": "musicId", "Artist" : "artist", "Song title" : "title"})
deam_metadata_2015

,musicId,title,artist
0,2001,Old Tree,Creepoid
1,2002,Spring Day 1,Amar Lal
2,2003,Excessive Resistance to Change,Joel Helander
3,2004,Flying,Aimee Norwich
4,2005,Waterduct,Ava Luna
5,2006,Air Traffic,Clara Berry and Wooldog
6,2007,Heavy Love,Dreamers of the Ghetto
7,2008,Disturbing Wildlife,Invisible Familiars
8,2009,Definition,Joel Helander
9,2010,Yatora,Karim Douaidy
10,2011,Toynbee Suite,Lushlife
11,2012,Impressions of Saturn,Matthew Entwistle
12,2013,The Arch,Matthew Entwistle
13,2014,You Listen,Meaxic
14,2015,Bester Jungling,NYU
15,2016,Chinese Jiang Nan,Music Delta
16,2017,Funk Jazz,Music Delta
17,2018,Modal Jazz,Music Delta
18,2019,The Broken Pledge - Chicago Reel,Phoenix
19,2020,The Collier's Daughter,Phoenix
20,2021,Stay Even,Port St Willow
21,2022,Mignon (Kennst du das Land) Op.92a Mvt.1,NYU
22,2023,Spacestation,Strand of Oaks
23,2024,Captain Sky,Tabla Breakbeat Science
24,2025,Rock Steady,Tabla Breakbeat Science
25,2026,Scorpio,Tabla Breakbeat Science
26,2027,Vermont,The Districts
27,2028,Les Fleurs Du Mal,The Scarlet Brand
28,2029,Night Owl,A Classic Education
29,2030,990,In Faded Glory
30,2031,Go,No
31,2032,Song For Jade,Kryptic Mood
32,2033,Uranium,Hunt Club
33,2034,Hey! beauty,Jacques COUTURIER
34,2035,Mit dem Unibalett im Ulmer Monster tanzen,Die Partysahnen
35,2036,Feel-ipson,Feel-ipson
36,2037,Dreamworld,engeo
37,2038,rouge et blues,Fabrice Collette
38,2039,Le Blues du Fantome,FOOL DADAZ FIRE
39,2040,FUCK THE WAR,Ralph Buckley
40,2041,Little White Church,Steven Dunston
41,2042,Classical Delay,Ogg Vorbis
42,2043,Summer,Matti Paalanen
43,2044,Habanera,Manuzik
44,2045,Jazzy Mode,Behrang Shegarfkar
45,2046,O Pindo,PELdeNOZ
46,2047,La note en cage,AdHoc
47,2048,Travelling in balochistan - late night highway,Maneros productions
48,2049,Lonely Fool,Steve.e!
49,2050,Homecoming,BeatRaider
50,2051,a fleur de peau,elbrujo
51,2052,Les 3 singes,Juice lee
52,2053,Neon,ADC LEVEL
53,2054,Interlude,Tom La Meche
54,2055,Vide grenier,Goo Goo Cluster
55,2056,happy child singing,Ruediger Kramer
56,2057,Au Feu,La Verue
57,2058,Inside Views,La Verue

In [ ]:
#without metadata 2014
deam_metadata = pd.concat([deam_metadata_2013, deam_metadata_2015])
deam_metadata

    musicId                          artist                          title
0         2  The New Mystikal Troubadours\t  \tTonight  A Lonely Century\t
1         3                 Kevin MacLeod\t                  \tDD Groove\t
2         4                 Kevin MacLeod\t                  \tSlow Burn\t
3         5                 My Bubba & Mi\t               \tNothing Much\t
4         7                 Kevin MacLeod\t                     \tHustle\t
..      ...                             ...                            ...
53     2054                    Tom La Meche                      Interlude
54     2055                 Goo Goo Cluster                   Vide grenier
55     2056                 Ruediger Kramer            happy child singing
56     2057                        La Verue                         Au Feu
57     2058                        La Verue                   Inside Views

[802 rows x 3 columns]

In [ ]:
deam_ann_2000 = pd.read_csv(DEAM_dataset+"/annotations/annotations averaged per song/song_level/static_annotations_averaged_songs_1_2000.csv", sep =",")
deam_ann_2058 = pd.read_csv(DEAM_dataset+"/annotations/annotations averaged per song/song_level/static_annotations_averaged_songs_2000_2058.csv", sep =",")

useful_columns = ["song_id", " valence_mean", " arousal_mean"]
deam_ann_2058 = deam_ann_2058[useful_columns].rename(columns = {"song_id":"musicId"," valence_mean": "Valence", " arousal_mean":"Arousal"})
deam_ann_2000 = deam_ann_2000[useful_columns].rename(columns = {"song_id":"musicId", " valence_mean": "Valence", " arousal_mean":"Arousal"})

print(deam_ann_2000.columns)
def normalize(col, min, max):
    return (col - min)/(max - min)

deam_ann_2000["Valence"] = normalize(deam_ann_2000["Valence"], 1, 10)
deam_ann_2000["Arousal"] = normalize(deam_ann_2000["Arousal"], 1, 10)

deam_ann_2058["Valence"] = normalize(deam_ann_2058["Valence"], 1, 10)
deam_ann_2058["Arousal"] = normalize(deam_ann_2058["Arousal"], 1, 10)

print(deam_ann_2000)
print(deam_ann_2058)

#Togliere file dei metadati del 2014 (o escludere titolo e artista degli altri)
#Prendere MP3
#Deam unico
#pmemo + deam

Index(['musicId', 'Valence', 'Arousal'], dtype='object')
      musicId   Valence   Arousal
0           2  0.233333  0.222222
1           3  0.277778  0.255556
2           4  0.522222  0.500000
3           5  0.377778  0.477778
4           7  0.533333  0.600000
...       ...       ...       ...
1739     1996  0.322222  0.544444
1740     1997  0.477778  0.322222
1741     1998  0.600000  0.577778
1742     1999  0.400000  0.488889
1743     2000  0.533333  0.555556

[1744 rows x 3 columns]
    musicId   Valence   Arousal
0      2001  0.244444  0.622222
1      2002  0.600000  0.466667
2      2003  0.488889  0.400000
3      2004  0.444444  0.422222
4      2005  0.311111  0.466667
5      2006  0.444444  0.244444
6      2007  0.266667  0.377778
7      2008  0.511111  0.288889
8      2009  0.466667  0.355556
9      2010  0.555556  0.422222
10     2011  0.355556  0.444444
11     2012  0.241111  0.463333
12     2013  0.488889  0.511111
13     2014  0.222222  0.622222
14     2015  0.622222  0.488889
15     2016  0.688889  0.511111
16     2017  0.630000  0.611111
17     2018  0.611111  0.592222
18     2019  0.644444  0.644444
19     2020  0.644444  0.533333
20     2021  0.355556  0.377778
21     2022  0.311111  0.377778
22     2023  0.511111  0.222222
23     2024  0.600000  0.377778
24     2025  0.555556  0.422222
25     2026  0.511111  0.333333
26     2027  0.533333  0.488889
27     2028  0.266667  0.577778
28     2029  0.352222  0.333333
29     2030  0.355556  0.577778
30     2031  0.400000  0.266667
31     2032  0.466667  0.377778
32     2033  0.241111  0.647778
33     2034  0.577778  0.400000
34     2035  0.266667  0.400000
35     2036  0.314444  0.407778
36     2037  0.600000  0.377778
37     2038  0.333333  0.311111
38     2039  0.488889  0.400000
39     2040  0.288889  0.666667
40     2041  0.377778  0.222222
41     2042  0.422222  0.400000
42     2043  0.511111  0.377778
43     2044  0.600000  0.466667
44     2045  0.422222  0.244444
45     2046  0.500000  0.463333
46     2047  0.577778  0.444444
47     2048  0.577778  0.288889
48     2049  0.377778  0.311111
49     2050  0.377778  0.288889
50     2051  0.244444  0.400000
51     2052  0.244444  0.466667
52     2053  0.311111  0.311111
53     2054  0.488889  0.288889
54     2055  0.444444  0.466667
55     2056  0.444444  0.400000
56     2057  0.241111  0.647778
57     2058  0.311111  0.533333

In [ ]:
deam_ann = pd.concat([deam_ann_2000[deam_ann_2000["musicId"] <= 1000], deam_ann_2058])

deam_ann

    musicId   Valence   Arousal
0         2  0.233333  0.222222
1         3  0.277778  0.255556
2         4  0.522222  0.500000
3         5  0.377778  0.477778
4         7  0.533333  0.600000
..      ...       ...       ...
53     2054  0.488889  0.288889
54     2055  0.444444  0.466667
55     2056  0.444444  0.400000
56     2057  0.241111  0.647778
57     2058  0.311111  0.533333

[802 rows x 3 columns]

In [ ]:
from pydub import AudioSegment

deam_audio = DEAM_dataset+"/MEMD_audio" 

deam_mp3 = pd.DataFrame([], columns=["musicId", "mp3_file"])
for file in os.listdir(deam_audio):
    audio, sr = librosa.load(os.path.join(deam_audio, file), sr=44100)
    #audio = AudioSegment.from_mp3(os.path.join(deam_audio, file))
    #audio = np.array(audio.get_array_of_samples())
    deam_mp3 = pd.concat([deam_mp3, pd.DataFrame([{"musicId": file.replace(".mp3",""), "mp3_file" :audio}])])

In [ ]:
deam_ann["musicId"] = deam_ann["musicId"].astype("str")
deam_mp3["musicId"] = deam_mp3["musicId"].astype("str")
deam_metadata["musicId"] = deam_metadata["musicId"].astype("str")

deam = deam_ann.join(deam_mp3.set_index("musicId"),on = "musicId")\
               .join(deam_metadata.set_index("musicId"), on = "musicId")

deam["musicId"] = deam["musicId"].astype("int").map(lambda x: x+1000)
deam

,musicId,Valence,Arousal,mp3_file,artist,title
0,1002,0.233333,0.222222,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",The New Mystikal Troubadours\t,\tTonight A Lonely Century\t
1,1003,0.277778,0.255556,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",Kevin MacLeod\t,\tDD Groove\t
2,1004,0.522222,0.500000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",Kevin MacLeod\t,\tSlow Burn\t
3,1005,0.377778,0.477778,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",My Bubba & Mi\t,\tNothing Much\t
4,1007,0.533333,0.600000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",Kevin MacLeod\t,\tHustle\t
...,...,...,...,...,...,...
53,3054,0.488889,0.288889,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",Tom La Meche,Interlude
54,3055,0.444444,0.466667,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",Goo Goo Cluster,Vide grenier
55,3056,0.444444,0.400000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",Ruediger Kramer,happy child singing
56,3057,0.241111,0.647778,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",La Verue,Au Feu
57,3058,0.311111,0.533333,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",La Verue,Inside Views

In [ ]:
songs = pd.concat([pmemo, deam]).drop(columns="album")
songs

,musicId,Arousal,Valence,title,artist,mp3_file
0,1,0.400000,0.575000,Good Drank,2 Chainz,"[0.0, -8.106964e-16, -5.9545294e-16, 1.866628e..."
1,4,0.262500,0.287500,X Bitch (feat. Future),21 Savage,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,5,0.150000,0.200000,No Heart,21 Savage,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,6,0.512500,0.350000,Red Opps,21 Savage,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,7,0.700000,0.725000,Girls Talk Boys,5 Seconds Of Summer,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...
53,3054,0.288889,0.488889,Interlude,Tom La Meche,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
54,3055,0.466667,0.444444,Vide grenier,Goo Goo Cluster,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
55,3056,0.400000,0.444444,happy child singing,Ruediger Kramer,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
56,3057,0.647778,0.241111,Au Feu,La Verue,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
57,3058,0.533333,0.311111,Inside Views,La Verue,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [ ]:
songs.to_pickle("../data/Songs")

In [ ]:
import sounddevice as sd
import random

rand_int = random.randint(0, len(songs))
print(songs.iloc[rand_int])
sd.play(songs["mp3_file"].iloc[rand_int], 44100)
sd.wait()

NameError: name 'songs' is not defined